version: "2"
services:
  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/tryu-fullerton-edu/AMSE_CPSC546_Cartelize
    container_name: accounts
    ports:
    - 8800:8082
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/tryu-fullerton-edu/AMSE_CPSC546_Cartelize
    container_name: auth
    ports: []
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/tryu-fullerton-edu/AMSE_CPSC546_Cartelize
    container_name: gateway
    ports: []
  inventory:
    build:
      context: .
      dockerfile: inventory/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/tryu-fullerton-edu/AMSE_CPSC546_Cartelize
    container_name: inventory
    ports: []
